import { useState, useCallback } from "react";
import { AgentType, LogEntry, FileNode, Agent } from "@/types/agent";
import { v4 as uuidv4 } from "uuid";

// Sample generated files
const SAMPLE_FILES: FileNode[] = [
  {
    name: "my-project",
    path: "my-project",
    type: "directory",
    children: [
      {
        name: "src",
        path: "my-project/src",
        type: "directory",
        children: [
          {
            name: "index.ts",
            path: "my-project/src/index.ts",
            type: "file",
            content: `import express from 'express';
import cors from 'cors';
import { router } from './routes/api';
import { errorHandler } from './middleware/errorHandler';

const app = express();
const PORT = process.env.PORT || 3000;

app.use(cors());
app.use(express.json());

app.use('/api', router);
app.use(errorHandler);

app.listen(PORT, () => {
  console.log(\`Server running on port \${PORT}\`);
});

export default app;`,
          },
          {
            name: "routes",
            path: "my-project/src/routes",
            type: "directory",
            children: [
              {
                name: "api.ts",
                path: "my-project/src/routes/api.ts",
                type: "file",
                content: `import { Router } from 'express';
import { TodoController } from '../controllers/todoController';

export const router = Router();
const todoController = new TodoController();

router.get('/todos', todoController.getAll);
router.get('/todos/:id', todoController.getById);
router.post('/todos', todoController.create);
router.put('/todos/:id', todoController.update);
router.delete('/todos/:id', todoController.delete);`,
              },
            ],
          },
          {
            name: "controllers",
            path: "my-project/src/controllers",
            type: "directory",
            children: [
              {
                name: "todoController.ts",
                path: "my-project/src/controllers/todoController.ts",
                type: "file",
                content: `import { Request, Response } from 'express';
import { TodoService } from '../services/todoService';

export class TodoController {
  private todoService = new TodoService();

  getAll = async (req: Request, res: Response) => {
    const todos = await this.todoService.findAll();
    res.json(todos);
  };

  getById = async (req: Request, res: Response) => {
    const todo = await this.todoService.findById(req.params.id);
    if (!todo) {
      return res.status(404).json({ error: 'Todo not found' });
    }
    res.json(todo);
  };

  create = async (req: Request, res: Response) => {
    const todo = await this.todoService.create(req.body);
    res.status(201).json(todo);
  };

  update = async (req: Request, res: Response) => {
    const todo = await this.todoService.update(req.params.id, req.body);
    res.json(todo);
  };

  delete = async (req: Request, res: Response) => {
    await this.todoService.delete(req.params.id);
    res.status(204).send();
  };
}`,
              },
            ],
          },
        ],
      },
      {
        name: "tests",
        path: "my-project/tests",
        type: "directory",
        children: [
          {
            name: "todo.test.ts",
            path: "my-project/tests/todo.test.ts",
            type: "file",
            content: `import request from 'supertest';
import app from '../src/index';

describe('Todo API', () => {
  it('should return empty array initially', async () => {
    const res = await request(app).get('/api/todos');
    expect(res.status).toBe(200);
    expect(res.body).toEqual([]);
  });

  it('should create a new todo', async () => {
    const res = await request(app)
      .post('/api/todos')
      .send({ title: 'Test Todo', completed: false });
    expect(res.status).toBe(201);
    expect(res.body.title).toBe('Test Todo');
  });
});`,
          },
        ],
      },
      {
        name: "package.json",
        path: "my-project/package.json",
        type: "file",
        content: `{
  "name": "my-project",
  "version": "1.0.0",
  "description": "Generated by AutoDev",
  "main": "dist/index.js",
  "scripts": {
    "start": "node dist/index.js",
    "dev": "ts-node-dev src/index.ts",
    "build": "tsc",
    "test": "jest"
  },
  "dependencies": {
    "express": "^4.18.2",
    "cors": "^2.8.5"
  },
  "devDependencies": {
    "@types/express": "^4.17.21",
    "@types/node": "^20.10.0",
    "typescript": "^5.3.0",
    "jest": "^29.7.0",
    "ts-jest": "^29.1.0",
    "supertest": "^6.3.3"
  }
}`,
      },
      {
        name: ".env.example",
        path: "my-project/.env.example",
        type: "file",
        content: `PORT=3000
NODE_ENV=development
DATABASE_URL=mongodb://localhost:27017/myproject`,
      },
      {
        name: "README.md",
        path: "my-project/README.md",
        type: "file",
        content: `# My Project

Generated by AutoDev Multi-Agent Platform

## Getting Started

\`\`\`bash
npm install
npm run dev
\`\`\`

## Testing

\`\`\`bash
npm test
\`\`\`

## API Endpoints

- GET /api/todos - Get all todos
- GET /api/todos/:id - Get todo by ID
- POST /api/todos - Create todo
- PUT /api/todos/:id - Update todo
- DELETE /api/todos/:id - Delete todo`,
      },
    ],
  },
];

const AGENT_STEPS: { agent: AgentType; messages: string[] }[] = [
  {
    agent: "parser",
    messages: [
      "Parsing user story...",
      "Identified requirements: REST API, CRUD operations, Express",
      "Extracting entities and relationships...",
      "Story parsing complete ✓",
    ],
  },
  {
    agent: "refiner",
    messages: [
      "Refining prompts for code generation...",
      "Optimizing context for Gemini API...",
      "Adding best practices hints...",
      "Prompt refinement complete ✓",
    ],
  },
  {
    agent: "codegen",
    messages: [
      "Generating project structure...",
      "Creating Express server...",
      "Generating controllers and routes...",
      "Adding TypeScript configuration...",
      "Code generation complete ✓",
    ],
  },
  {
    agent: "file",
    messages: [
      "Initializing workspace directory...",
      "Writing source files...",
      "Creating configuration files...",
      "Initializing Git repository...",
      "File management complete ✓",
    ],
  },
  {
    agent: "test",
    messages: [
      "Installing dependencies...",
      "Running npm install...",
      "Executing test suite...",
      "All tests passed (2/2) ✓",
    ],
  },
  {
    agent: "reviewer",
    messages: [
      "Analyzing code quality...",
      "Checking TypeScript types...",
      "Verifying best practices...",
      "Code review complete: Grade A ✓",
    ],
  },
];

export function useAgentSimulation() {
  const [logs, setLogs] = useState<LogEntry[]>([]);
  const [files, setFiles] = useState<FileNode[]>([]);
  const [isRunning, setIsRunning] = useState(false);
  const [activeAgent, setActiveAgent] = useState<AgentType | undefined>();
  const [agentStatuses, setAgentStatuses] = useState<Record<AgentType, Agent["status"]>>({
    parser: "idle",
    refiner: "idle",
    codegen: "idle",
    file: "idle",
    test: "idle",
    reviewer: "idle",
  });

  const addLog = useCallback((agent: AgentType, message: string, type: LogEntry["type"] = "info") => {
    const entry: LogEntry = {
      id: uuidv4(),
      timestamp: new Date(),
      agent,
      message,
      type,
    };
    setLogs((prev) => [...prev, entry]);
  }, []);

  const runSimulation = useCallback(async (projectName: string, story: string) => {
    setIsRunning(true);
    setLogs([]);
    setFiles([]);
    setAgentStatuses({
      parser: "idle",
      refiner: "idle",
      codegen: "idle",
      file: "idle",
      test: "idle",
      reviewer: "idle",
    });

    addLog("parser", `Starting new project: ${projectName}`, "info");
    addLog("parser", `User story: ${story.substring(0, 50)}...`, "info");

    for (const step of AGENT_STEPS) {
      setActiveAgent(step.agent);
      setAgentStatuses((prev) => ({ ...prev, [step.agent]: "running" }));

      for (const message of step.messages) {
        await new Promise((resolve) => setTimeout(resolve, 500 + Math.random() * 500));
        addLog(
          step.agent,
          message,
          message.includes("✓") ? "success" : "info"
        );
      }

      setAgentStatuses((prev) => ({ ...prev, [step.agent]: "completed" }));
      await new Promise((resolve) => setTimeout(resolve, 300));
    }

    // Update file names to match project name
    const updatedFiles = SAMPLE_FILES.map((file) => ({
      ...file,
      name: projectName,
      path: projectName,
      children: file.children?.map((child) => ({
        ...child,
        path: child.path.replace("my-project", projectName),
        children: child.children?.map((subChild) => ({
          ...subChild,
          path: subChild.path.replace("my-project", projectName),
          children: subChild.children?.map((deepChild) => ({
            ...deepChild,
            path: deepChild.path.replace("my-project", projectName),
          })),
        })),
      })),
    }));

    setFiles(updatedFiles);
    setActiveAgent(undefined);
    setIsRunning(false);
    addLog("reviewer", `Project ${projectName} generated successfully!`, "success");
  }, [addLog]);

  const reset = useCallback(() => {
    setLogs([]);
    setFiles([]);
    setIsRunning(false);
    setActiveAgent(undefined);
    setAgentStatuses({
      parser: "idle",
      refiner: "idle",
      codegen: "idle",
      file: "idle",
      test: "idle",
      reviewer: "idle",
    });
  }, []);

  return {
    logs,
    files,
    isRunning,
    activeAgent,
    agentStatuses,
    runSimulation,
    reset,
  };
}
